[theme]
base = "light"
primaryColor = "#4A90E2"  # Soft blue for accents
backgroundColor = "#f9f9f9"  # Soft off-white
secondaryBackgroundColor = "#f0f2f5"  
textColor = "#1f1f1f"  #
font = "sans serif"

[server]
runOnSave = true