#############################################
# Active Providers
#############################################
[providers]
active = ["openai", "xai", "huggingface", "anthropic"] # first one is the default

[provider_labels]
anthropic   = "Anthropic"
huggingface = "Hugging Face"
openai      = "OpenAI"
xai         = "x.ai"

#############################################
# Provider Configurations
#############################################

[anthropic]
api_key   = "YOUR_ANTHROPIC_API_KEY"
model     = "claude-3-5-haiku-20241022" # or claude-3-7-sonnet-20250219
base_url  = "https://api.anthropic.com/v1/"  # Beta support for OpenAI SDK

[huggingface]
api_key   = "YOUR_HF_API_KEY"
model     = "meta-llama/Llama-2-70b-chat-hf"
base_url  = "https://your-hf-endpoint.com/v1/"  # Replace with your actual HF endpoint

[openai]
api_key   = "YOUR_OPENAI_API_KEY"
model     = "gpt-4o"
base_url  = "https://api.openai.com/v1"

[xai]
api_key   = "YOUR_GROK_API_KEY"
model     = "grok-2-latest"
base_url  = "https://api.x.ai/v1"